---
apiVersion: batch/v1
kind: Job
metadata:
  name: hostapd
  namespace: turnkey
spec:
  template:
    metadata:
      labels:
        turnkey/workloadselector: job-turnkey-hostapd
    spec:
      containers:
      - args:
        - up
        image: mak3r/hostapd:v0.0.10
        imagePullPolicy: IfNotPresent
        name: hostapd
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_ADMIN
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        volumeMounts:
          - mountPath: /conf
            name: ap-config
          - mountPath: /var/lib/rancher/turnkey/status
            name: status
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      initContainers:
      - name: ssids-listed
        image: busybox:1.28
        command: ['sh', '-c', "until [ $(wc -l /var/lib/rancher/turnkey/ssid.list | awk '{print $1}') -gt 0 ]; do echo waiting for wifi ap list; sleep 2; done"]
        volumeMounts:
          - mountPath: /var/lib/rancher/turnkey/ssid.list
            name: ssids
      volumes:
      - name: ssids
        hostPath:
          path: /tmp/ssid.list
          type: FileOrCreate
      - name: status
        hostPath:
          path: /tmp/status
          type: FileOrCreate
      - name: ap-config
        configMap:
          name: ap-config
          optional: false
          items:
          - key: hostapd.conf
            path: hostapd.conf
          - key: dnsmasq.conf
            path: dnsmasq.conf
          - key: dhcpcd.conf
            path: dhcpcd.conf
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: batch/v1
kind: Job
metadata:
  name: ui
  namespace: turnkey
spec:
  template:
    metadata:
      labels:
        turnkey/workloadselector: job-turnkey-ui
    spec:
      initContainers:
        - args:
          - scan
          image: mak3r/wifi:v0.0.10
          imagePullPolicy: IfNotPresent
          name: ssid-scan
          resources: {}
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
              - NET_ADMIN
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
          - mountPath: /tmp
            name: vol1
          - mountPath: /var/lib/rancher/turnkey
            name: vol4
        - name: has-networks
          volumeMounts:
            - mountPath: /tmp
              name: vol1
          image: busybox:1.28
          command: ['grep', '-E', '[^\s]', /tmp/ssid.list]
      containers:
      - image: mak3r/turnkey-ui:v0.0.24
        imagePullPolicy: IfNotPresent
        name: ui
        ports:
        - containerPort: 80
          hostPort: 80
          name: 80tcp800
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /tmp
          name: vol1
        - mountPath: /etc/machine-id
          name: vol2
        - mountPath: /var/lib/rancher/k3s/server/manifests
          name: vol3
        - mountPath: /var/lib/rancher/turnkey
          name: vol4
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      hostNetwork: true
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /tmp
          type: Directory
        name: vol1
      - hostPath:
          path: /etc/machine-id
          type: File
        name: vol2
      - hostPath:
          path: /var/lib/rancher/k3s/server/manifests
          type: Directory
        name: vol3
--- 
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: turnkey
spec:
  ports:
  - name: 80tcp01-ui
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    turnkey/workloadselector: job-turnkey-ui
  sessionAffinity: None
  type: ClusterIP
--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: ap-config
  namespace: turnkey
data:
  hostapd.conf: |
    interface=wlan0
    driver=nl80211
    ssid=ConfigureK3s
    hw_mode=a
    channel=44
    ieee80211d=1
    country_code=US
    ieee80211n=1
    ieee80211ac=1
    wmm_enabled=0
    macaddr_acl=0
    auth_algs=1
    ignore_broadcast_ssid=0
    #wpa=2
    #wpa_passphrase=rancher-k3s
    #wpa_key_mgmt=WPA-PSK
    #wpa_pairwise=TKIP
    #rsn_pairwise=CCMP
  dnsmasq.conf: |
    interface=wlan0
    dhcp-range=192.168.4.2,192.168.4.20,255.255.255.0,24h
  dhcpcd.conf: |
    interface wlan0
      static ip_address=192.168.4.1/24
      nohook wpa_supplicant
